saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.order_list, name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/cancel/$',
        views.cancel_order, name='order-cancel'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$',
        views.orderline_split, name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<order_pk>\d+)/remove-voucher/$',
        views.remove_order_voucher, name='order-remove-voucher'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$',
        views.ship_delivery_group, name='ship-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/cancel/$',
        views.cancel_delivery_group, name='cancel-delivery-group')]

saleor/dashboard/urls.py
from django.conf.urls import url, include

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .customer.urls import urlpatterns as customer_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .discount.urls import urlpatterns as discount_urls
from .search.urls import urlpatterns as search_urls
from .sites.urls import urlpatterns as site_urls
from .shipping.urls import urlpatterns as shipping_urls


urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^customers/', include(customer_urls)),
    url(r'^discounts/', include(discount_urls)),
    url(r'^search/', include(search_urls)),
    url(r'^settings/', include(site_urls)),
    url(r'^shipping/', include(shipping_urls)),
    url(r'^style-guide/', core_views.styleguide, name='styleguide'),
]

saleor/order/urls.py
from django.conf.urls import url

from ..core import TOKEN_PATTERN
from . import views


urlpatterns = [
    url(r'^%s/$' % (TOKEN_PATTERN,), views.details, name='details'),
    url(r'^%s/payment/$' % (TOKEN_PATTERN,),
        views.payment, name='payment'),
    url(r'^%s/payment/(?P<variant>[-\w]+)/$' % (TOKEN_PATTERN,),
        views.start_payment, name='payment'),
    url(r'^%s/cancel-payment/$' % (TOKEN_PATTERN,), views.cancel_payment,
        name='cancel-payment'),
    url(r'^%s/create-password/$' % (TOKEN_PATTERN,),
        views.create_password, name='create-password'),
    url(r'^%s/attach/$' % (TOKEN_PATTERN,),
        views.connect_order_with_user, name='connect-order-with-user'),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls
from .userprofile.views import pathfind
urlpatterns = [
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #url(r'^admin/', include(admin.site.urls))
    url(r'^', include(core_urls)),
    url(r'^account/', include(registration_urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^search/', include(search_urls, namespace='search')),
    url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap'),
    url(r'^pathfind/', pathfind),
    
        
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social')),
    
    
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/dashboard/search/forms.py
from ...search.backends import get_search_backend
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):

    def search(self, queryset_map=None):
        backend = get_search_backend('dashboard')
        query = self.cleaned_data['q']
        results = backend.search(query, queryset_map=queryset_map)
        return results

saleor/dashboard/category/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy

from ...product.models import Category
from ..views import staff_member_required
from .forms import CategoryForm


@staff_member_required
def category_list(request, root_pk=None):
    root = None
    path = None
    categories = Category.tree.root_nodes()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
        categories = root.get_children()
    ctx = {'categories': categories, 'path': path, 'root': root}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
def category_create(request, root_pk=None):
    category = Category()
    form = CategoryForm(request.POST or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
def category_edit(request, root_pk=None):
    category = get_object_or_404(Category, pk=root_pk)
    form = CategoryForm(request.POST or None, instance=category,
                        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Updated category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status}
    template = 'dashboard/category/modal_edit.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Deleted category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {'redirectUrl': reverse(
                    'dashboard:category-list', kwargs={'root_pk': root_pk})}
                return JsonResponse(response)
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            if request.is_ajax():
                response = {'redirectUrl': reverse('dashboard:category-list')}
                return JsonResponse(response)
            return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(request,
                            'dashboard/category/modal_delete.html',
                            ctx)

saleor/dashboard/customer/views.py
from __future__ import unicode_literals

from django.db.models import Count, Max
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse

from ..views import staff_member_required
from ...core.utils import get_paginator_items
from ...userprofile.models import User


@staff_member_required
def customer_list(request):
    customers = (
        User.objects
        .prefetch_related('orders', 'addresses')
        .select_related('default_billing_address', 'default_shipping_address')
        .annotate(
            num_orders=Count('orders', distinct=True),
            last_order=Max('orders', distinct=True)))
    customers = get_paginator_items(customers, 30, request.GET.get('page'))
    ctx = {'customers': customers}
    return TemplateResponse(request, 'dashboard/customer/list.html', ctx)


@staff_member_required
def customer_details(request, pk):
    queryset = User.objects.prefetch_related(
        'orders', 'addresses').select_related('default_billing_address')
    customer = get_object_or_404(queryset, pk=pk)
    customer_orders = customer.orders.all()
    ctx = {'customer': customer, 'customer_orders': customer_orders}
    return TemplateResponse(request, 'dashboard/customer/detail.html', ctx)

saleor/dashboard/discount/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy

from ...discount.models import Sale, Voucher
from . import forms


@staff_member_required
def sale_list(request):
    sales = Sale.objects.prefetch_related('products')
    ctx = {'sales': sales}
    return TemplateResponse(request, 'dashboard/discount/sale_list.html', ctx)


@staff_member_required
def sale_edit(request, pk=None):
    if pk:
        instance = get_object_or_404(Sale, pk=pk)
    else:
        instance = Sale()
    form = forms.SaleForm(
        request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save()
        msg = pgettext_lazy(
            'Sale (discount) message', 'Updated sale') if pk else pgettext_lazy(
                'Sale (discount) message', 'Added sale')
        messages.success(request, msg)
        return redirect('dashboard:sale-update', pk=instance.pk)
    ctx = {'sale': instance, 'form': form}
    return TemplateResponse(request, 'dashboard/discount/sale_form.html', ctx)


@staff_member_required
def sale_delete(request, pk):
    instance = get_object_or_404(Sale, pk=pk)
    if request.method == 'POST':
        instance.delete()
        messages.success(
            request,
            pgettext_lazy('Sale (discount) message', 'Deleted sale %s') % (instance.name,))
        return redirect('dashboard:sale-list')
    ctx = {'sale': instance}
    return TemplateResponse(
        request, 'dashboard/discount/sale_modal_confirm_delete.html', ctx)


@staff_member_required
def voucher_list(request):
    vouchers = Voucher.objects.select_related('product', 'category')
    ctx = {'vouchers': vouchers}
    return TemplateResponse(
        request, 'dashboard/discount/voucher_list.html', ctx)


@staff_member_required
def voucher_edit(request, pk=None):
    if pk is not None:
        instance = get_object_or_404(Voucher, pk=pk)
    else:
        instance = Voucher()
    voucher_form = forms.VoucherForm(request.POST or None, instance=instance)
    type_base_forms = {
        Voucher.SHIPPING_TYPE: forms.ShippingVoucherForm(
            request.POST or None, instance=instance,
            prefix=Voucher.SHIPPING_TYPE),
        Voucher.VALUE_TYPE: forms.ValueVoucherForm(
            request.POST or None, instance=instance,
            prefix=Voucher.VALUE_TYPE),
        Voucher.PRODUCT_TYPE: forms.ProductVoucherForm(
            request.POST or None, instance=instance,
            prefix=Voucher.PRODUCT_TYPE),
        Voucher.CATEGORY_TYPE: forms.CategoryVoucherForm(
            request.POST or None, instance=instance,
            prefix=Voucher.CATEGORY_TYPE)}
    if voucher_form.is_valid():
        voucher_type = voucher_form.cleaned_data['type']
        form_type = type_base_forms.get(voucher_type)
        if form_type is None:
            instance = voucher_form.save()
        elif form_type.is_valid():
            instance = form_type.save()

        if form_type is None or form_type.is_valid():
            msg = pgettext_lazy(
                'Voucher message', 'Updated voucher') if pk else pgettext_lazy(
                    'Voucher message', 'Added voucher')
            messages.success(request, msg)
            return redirect('dashboard:voucher-update', pk=instance.pk)
    ctx = {
        'voucher': instance, 'default_currency': settings.DEFAULT_CURRENCY,
        'form': voucher_form, 'type_base_forms': type_base_forms}
    return TemplateResponse(
        request, 'dashboard/discount/voucher_form.html', ctx)


@staff_member_required
def voucher_delete(request, pk):
    instance = get_object_or_404(Voucher, pk=pk)
    if request.method == 'POST':
        instance.delete()
        messages.success(
            request,
            pgettext_lazy('Voucher message', 'Deleted voucher %s') % (instance,))
        return redirect('dashboard:voucher-list')
    ctx = {'voucher': instance}
    return TemplateResponse(
        request, 'dashboard/discount/voucher_modal_confirm_delete.html', ctx)

saleor/dashboard/search/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from django.shortcuts import render

from ...order.models import Order
from ...product.models import Product
from ...search.views import paginate_results
from ...userprofile.models import User
from .forms import DashboardSearchForm


@staff_member_required
def search(request):
    form = DashboardSearchForm(data=request.GET or None)
    query = ''
    queryset_map = {
        Product: Product.objects.prefetch_related('images'),
        Order: Order.objects.prefetch_related('user'),
        User: User.objects.all()}
    if form.is_valid():
        results = form.search(queryset_map=queryset_map)
        page = paginate_results(results, request.GET, settings.PAGINATE_BY)
        query = form.cleaned_data['q']
    else:
        page = []
    ctx = {
        'form': form,
        'query': query,
        'results': page,
        'query_string': '?q=%s' % query}
    return render(request, 'dashboard/search/results.html', ctx)

saleor/dashboard/sites/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import ugettext_lazy as _

from .forms import AuthorizationKeyFormSet, SiteSettingForm
from ..views import staff_member_required
from ...site.models import AuthorizationKey, SiteSettings
from ...site.utils import get_site_settings_from_request


@staff_member_required
def index(request):
    settings = get_site_settings_from_request(request)
    return redirect('dashboard:site-update', site_id=settings.pk)


@staff_member_required
def update(request, site_id=None):
    site = get_object_or_404(SiteSettings, pk=site_id)
    form = SiteSettingForm(request.POST or None, instance=site)
    authorization_qs = AuthorizationKey.objects.filter(site_settings=site)
    formset = AuthorizationKeyFormSet(
        request.POST or None, queryset=authorization_qs,
        initial=[{'site_settings': site}])
    if all([form.is_valid(), formset.is_valid()]):
        site = form.save()
        formset.save()
        messages.success(request, _('Updated site %s') % site)
        return redirect('dashboard:site-update', site_id=site.id)
    ctx = {'site': site, 'form': form, 'formset': formset}
    return TemplateResponse(request, 'dashboard/sites/detail.html', ctx)

templates/dashboard/order/address_form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load staticfiles %}

{% block title %}
  {% trans "Edit address" context "" %} - {% trans "Orders" context "Dashboard orders list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-orders{% endblock %}

{% block menu_orders_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:orders" as url %}
  {% include "dashboard/includes/_back-link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:orders" %}">
        {% trans "Orders" context "Dashboard orders list" %}
      </a>
    </li>
    <li class="hide-on-med-and-down">
      <a href="{% url "dashboard:order-details" order_pk=order.pk %}">
        #{{ order.pk }}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:order-details" order_pk=order.pk %}">
        <svg data-src="{% static "dashboard/images/arrow_left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% if address_type == "shipping" %}
          {% trans "Shipping address" context "" %}
        {% else %}
          {% trans "Billing address" context "" %}
        {% endif %}
      </span>
    </li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 m9">
      <div class="card">
        <form method="post" novalidate>
          <div class="card-content">
            {% csrf_token %}
            <div class="row">
              {{ form|materializecss }}
            </div>
          </div>
          <div class="card-action right-align">
            <a href="{% url "dashboard:order-details" order_pk=order.pk %}" class="btn btn-flat">
              {% trans "Cancel" context "Dashboard cancel action" %}
            </a>
            <button type="submit" class="btn waves-effect waves-light">
              {% trans "Update" context "Dashboard update action" %}
            </button>
          </div>
        </form>
      </div>
    </div>
    <div class="col s12 m3"></div>
  </div>
{% endblock %}

templates/dashboard/order/modal_add_note.html
{% load i18n %}
{% load materializecss %}

<form role="form" method="post" action="{% url 'dashboard:order-add-note' order_pk=order.pk %}" class="form-async" novalidate>
  {% csrf_token %}
  <div class="modal-content">
    <h5>
      {% trans "Add note" context "Modal add note title" %}
    </h5>
    <div class="row">
      {{ form|materializecss }}
    </div>
  </div>
  <div class="modal-footer">
    <button type="submit" class="modal-action btn-flat">
      {% trans "Save note" context "Modal add note primary action" %}
    </button>
    <a href="#!" class="modal-action modal-close btn-flat">
      {% trans "Cancel" context "Dashboard cancel action" %}
    </a>
  </div>
</form>

templates/dashboard/order/modal_cancel_delivery_group.html
{% load i18n %}
{% load materializecss %}

<form id="ship-delivery-group-form" method="post" role="form" action="{% url 'dashboard:cancel-delivery-group' order_pk=order.pk group_pk=group.pk %}" class="form-async" novalidate>
  {% csrf_token %}
  <div class="modal-content">
    <h5>
      {% trans "Cancel delivery group?" context "Modal cancel delivery group title" %}
    </h5>
    <p>
      {% blocktrans trimmed context "Modal cancel delivery group text" %}
        After this action {{ group }} will be cancelled. Ordered items will be returned to stock.
      {% endblocktrans %}
    </p>
  </div>
  <div class="modal-footer">
    <button type="submit" class="modal-action btn-flat">
      {% trans "Cancel this shipment" context "Modal cancel delivery group primary action" %}
    </button>
    <a href="#!" aria-hidden="true" class="modal-action modal-close btn-flat">
      {% trans "Abort" context "Dashboard abort action" %}
    </a>
  </div>
</form>

templates/dashboard/order/modal_cancel_line.html
{% load i18n %}
{% load materializecss %}
{% load prices_i18n %}

<form class="form-async" role="form" method="post" action="{% url 'dashboard:orderline-cancel' order_pk=order.pk line_pk=item.pk %}" novalidate>
  {% csrf_token %}
  <div class="modal-content">
    <h5>
      {% trans "Remove order line?" context "Modal remove order line title" %}
    </h5>
    <p>
      {% blocktrans trimmed with order=order context "Modal remove order line text" %}
        Are you sure you want remove this order line?
      {% endblocktrans %}
    </p>
    {{ form|materializecss }}
    <table>
      <thead>
        <tr>
          <th class="wide">
            {% trans "Item" context "Modal remove order line table header" %}
          </th>
          <th>
            {% trans "SKU" context "Modal remove order line table header" %}
          </th>
          <th class="right-align">
            {% trans "Price" context "Modal remove order line table header" %}
          </th>
          <th class="right-align">
            {% trans "Quantity" context "Modal remove order line table header" %}
          </th>
          <th class="right-align">
            {% trans "Total" context "Modal remove order line table header" %}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            {{ item.product_name }}<br>
          </td>
          <td>
            {{ item.product_sku }}
          </td>
          <td class="right-align">
            {% gross item.get_price_per_item html=True %}
          </td>
          <td class="right-align">
            {{ item.quantity }}
          </td>
          <td class="right-align">
            {% gross item.get_total html=True %}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="modal-footer">
    <button type="submit" class="modal-action btn-flat">
      {% trans "Remove" context "Dashboard remove action" %}
    </button>
    <a href="#!" aria-hidden="true" class="modal-action modal-close btn-flat">
      {% trans "Cancel" context "Dashboard cancel action" %}
    </a>
  </div>
</form>

templates/dashboard/order/modal_cancel_order.html
{% load i18n %}
{% load materializecss %}

<div class="modal-content">
  <h5>
    {% trans "Cancel order?" context "Modal cancel order title" %}
  </h5>
  <p>
    {% blocktrans trimmed with order=order context "Modal cancel order text" %}
      Are you sure, you want cancel order {{ order }}?
    {% endblocktrans %}
  </p>
</div>

<div class="modal-footer">
  <form id="release-form" method="post" role="form" class="form-async"
  action="{% url 'dashboard:order-cancel' order_pk=order.pk %}" novalidate>
    {% csrf_token %}
    <button type="submit" class="modal-action btn-flat">
      {% trans "Cancel Order" context "Modal cancel order primary action" %}
    </button>
    <a href="#!" aria-hidden="true" class="modal-action modal-close btn-flat">
      {% trans "Abort" context "Dashboard abort action" %}
    </a>
  </form>
</div>

templates/dashboard/order/modal_capture.html
{% load i18n %}
{% load babel %}
{% load materializecss %}
{% load prices_i18n %}

<form role="form" method="post" action="{% url 'dashboard:capture-payment' order_pk=order.pk payment_pk=payment.pk %}" class="form-async" novalidate>
  {% csrf_token %}
  <div class="modal-content">
    <h5>
      {% trans "Capture payment" context "Modal capture payment title" %}
    </h5>
    <div class="row">
      {{ form|materializecss }}
    </div>
    <h5>
      {% trans "Before this action" context "Modal capture payment title" %}
    </h5>
    <ul class="list">
      <li class="list-item">{% trans "Order total:" context "Modal capture payment list title" %}
        {% gross payment.order.get_total html=True %}
      </li>
      <li class="list-item">{% trans "Captured amount:" context "Modal capture payment list title" %}
        {{ captured|currencyfmt:currency }}
      </li>
    </ul>
  </div>
  <div class="modal-footer">
    <button type="submit" class="modal-action btn-flat">
      {% trans "Capture" context "Modal capture payment primary action" %}
    </button>
    <a href="#!" aria-hidden="true" class="modal-action modal-close btn-flat">
      {% trans "Cancel" context "Dashboard cancel action" %}
    </a>
  </div>
</form>

templates/dashboard/order/modal_change_quantity.html
{% load i18n %}
{% load materializecss %}

<form method="post" role="form" action="{% url 'dashboard:orderline-change-quantity' order_pk=order.pk line_pk=object.pk %}" class="form-async" novalidate>
  {% csrf_token %}
  <div class="modal-content">
    <h5>
      {% trans "Change quantity" context "Modal change quantity title" %}
    </h5>
    <div class="row">
      {{ form|materializecss:"s12 m6" }}
    </div>
  </div>
  <div class="modal-footer">
    <button type="submit" class="modal-action btn-flat">
      {% trans "Update" context "Dashboard update action" %}
    </button>
    <a href="#!" aria-hidden="true" class="modal-action modal-close btn-flat">
      {% trans "Cancel" context "Dashboard cancel action" %}
    </a>
  </div>
</form>

templates/dashboard/order/modal_order_remove_voucher.html
{% load i18n %}
{% load materializecss %}

<div class="modal-content">
  <h5>
    {% trans "Remove voucher?" context "Modal remove voucher from order title" %}
  </h5>
  <p>
    {% blocktrans trimmed with order=order context "Modal remove voucher from order text" %}
      Are you sure, you want remove voucher discount from {{ order }}?
    {% endblocktrans %}
  </p>
</div>
<div class="modal-footer">
  <form id="release-form" method="post" role="form" class="form-async"
  action="{% url 'dashboard:order-remove-voucher' order_pk=order.pk %}" novalidate>
    {% csrf_token %}
    <button type="submit" class="modal-action btn-flat">
      {% trans "Remove voucher" context "Modal remove voucher from order primary action" %}
    </button>
    <a href="#!" aria-hidden="true" class="modal-action modal-close btn-flat">
      {% trans "Abort" context "Dashboard abort action" %}
    </a>
  </form>
</div>

templates/dashboard/order/modal_refund.html
{% load i18n %}
{% load babel %}
{% load materializecss %}
{% load prices_i18n %}

<form role="form" method="post" action="{% url 'dashboard:refund-payment' order_pk=order.pk payment_pk=payment.pk %}" class="form-async" novalidate>
  {% csrf_token %}
  <div class="modal-content">
    <h5>
      {% trans "Refund payment" context "Modal refund payment title" %}
    </h5>
    <div class="row">
      {{ form|materializecss }}
    </div>
    <h5>
      {% trans "Before this action" context "Modal refund payment title" %}
    </h5>
    <ul class="list">
      <li class="list-item">{% trans "Order total:" context "Modal refund payment list title" %}
        {% gross payment.order.get_total html=True %}
      </li>
      <li class="list-item">{% trans "Captured amount:" context "Modal refund payment list title" %}
        {{ captured|currencyfmt:currency }}
      </li>
    </ul>
  </div>
  <div class="modal-footer">
    <button type="submit" class="modal-action btn-flat">
      {% trans "Refund" context "Modal refund payment primary action" %}
    </button>
    <a href="#!" aria-hidden="true" class="modal-action modal-close btn-flat">
      {% trans "Cancel" context "Dashboard cancel action" %}
    </a>
  </div>
</form>