saleor/cart/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^update/(?P<variant_id>\d+)/$', views.update, name='update-line'),
    url(r'^summary/$', views.summary, name='cart-summary'),
    url(r'^shipingoptions/$', views.get_shipping_options,
        name='shipping-options')
]

saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.order_list, name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/cancel/$',
        views.cancel_order, name='order-cancel'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$',
        views.orderline_split, name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<order_pk>\d+)/remove-voucher/$',
        views.remove_order_voucher, name='order-remove-voucher'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$',
        views.ship_delivery_group, name='ship-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/cancel/$',
        views.cancel_delivery_group, name='cancel-delivery-group')]

saleor/order/urls.py
from django.conf.urls import url

from ..core import TOKEN_PATTERN
from . import views


urlpatterns = [
    url(r'^%s/$' % (TOKEN_PATTERN,), views.details, name='details'),
    url(r'^%s/payment/$' % (TOKEN_PATTERN,),
        views.payment, name='payment'),
    url(r'^%s/payment/(?P<variant>[-\w]+)/$' % (TOKEN_PATTERN,),
        views.start_payment, name='payment'),
    url(r'^%s/cancel-payment/$' % (TOKEN_PATTERN,), views.cancel_payment,
        name='cancel-payment'),
    url(r'^%s/create-password/$' % (TOKEN_PATTERN,),
        views.create_password, name='create-password'),
    url(r'^%s/attach/$' % (TOKEN_PATTERN,),
        views.connect_order_with_user, name='connect-order-with-user'),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls
from .userprofile.views import pathfind
urlpatterns = [
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #url(r'^admin/', include(admin.site.urls))
    url(r'^', include(core_urls)),
    url(r'^account/', include(registration_urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^search/', include(search_urls, namespace='search')),
    url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap'),
    url(r'^pathfind/', pathfind),
    
        
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social')),
    
    
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/cart/models.py
from __future__ import unicode_literals

from collections import namedtuple
from decimal import Decimal
from prices import Price
from uuid import uuid4

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.encoding import python_2_unicode_compatible, smart_str
from django.utils.timezone import now
from django.utils.translation import pgettext_lazy
from django_prices.models import PriceField
from jsonfield import JSONField
from satchless.item import ItemLine, ItemList, partition

from . import CartStatus, logger


CENTS = Decimal('0.01')
SimpleCart = namedtuple('SimpleCart', ('quantity', 'total', 'token'))


class ProductGroup(ItemList):
    def is_shipping_required(self):
        return any(p.is_shipping_required() for p in self)


class CartQueryset(models.QuerySet):

    def anonymous(self):
        return self.filter(user=None)

    def open(self):
        return self.filter(status=CartStatus.OPEN)

    def saved(self):
        return self.filter(status=CartStatus.SAVED)

    def waiting_for_payment(self):
        return self.filter(status=CartStatus.WAITING_FOR_PAYMENT)

    def checkout(self):
        return self.filter(status=CartStatus.CHECKOUT)

    def canceled(self):
        return self.filter(status=CartStatus.CANCELED)

    def for_display(self):
        return self.prefetch_related(
            'lines__variant__product__categories',
            'lines__variant__product__images',
            'lines__variant__product__product_class__product_attributes__values',  # noqa
            'lines__variant__product__product_class__variant_attributes__values',  # noqa
            'lines__variant__stock')


class Cart(models.Model):
    status = models.CharField(
        pgettext_lazy('Cart field', 'order status'),
        max_length=32, choices=CartStatus.CHOICES, default=CartStatus.OPEN)
    created = models.DateTimeField(
        pgettext_lazy('Cart field', 'created'), auto_now_add=True)
    last_status_change = models.DateTimeField(
        pgettext_lazy('Cart field', 'last status change'), auto_now_add=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, blank=True, null=True, related_name='carts',
        verbose_name=pgettext_lazy('Cart field', 'user'))
    email = models.EmailField(
        pgettext_lazy('Cart field', 'email'), blank=True, null=True)
    token = models.UUIDField(
        pgettext_lazy('Cart field', 'token'),
        primary_key=True, default=uuid4, editable=False)
    voucher = models.ForeignKey(
        'discount.Voucher', null=True, related_name='+',
        on_delete=models.SET_NULL,
        verbose_name=pgettext_lazy('Cart field', 'token'))
    checkout_data = JSONField(
        verbose_name=pgettext_lazy('Cart field', 'checkout data'), null=True,
        editable=False,)

    total = PriceField(
        pgettext_lazy('Cart field', 'total'),
        currency=settings.DEFAULT_CURRENCY, max_digits=12, decimal_places=2,
        default=0)
    quantity = models.PositiveIntegerField(
        pgettext_lazy('Cart field', 'quantity'), default=0)

    objects = CartQueryset.as_manager()

    class Meta:
        ordering = ('-last_status_change',)
        verbose_name = pgettext_lazy('Cart model', 'Cart')
        verbose_name_plural = pgettext_lazy('Cart model', 'Carts')

    def __init__(self, *args, **kwargs):
        self.discounts = kwargs.pop('discounts', None)
        super(Cart, self).__init__(*args, **kwargs)

    def update_quantity(self):
        total_lines = self.count()['total_quantity']
        if not total_lines:
            total_lines = 0
        self.quantity = total_lines
        self.save(update_fields=['quantity'])

    def change_status(self, status):
        if status not in dict(CartStatus.CHOICES):
            raise ValueError('Not expected status')
        if status != self.status:
            self.status = status
            self.last_status_change = now()
            self.save()

    def change_user(self, user):
        open_cart = Cart.get_user_open_cart(user)
        if open_cart is not None:
            open_cart.change_status(status=CartStatus.CANCELED)
        self.user = user
        self.save(update_fields=['user'])

    @staticmethod
    def get_user_open_cart(user):
        carts = user.carts.open()
        if len(carts) > 1:
            logger.warning('%s has more than one open basket', user)
            for cart in carts[1:]:
                cart.change_status(CartStatus.CANCELED)
        return carts.first()

    def is_shipping_required(self):
        return any(line.is_shipping_required() for line in self.lines.all())

    def __repr__(self):
        return 'Cart(quantity=%s)' % (self.quantity,)

    def __len__(self):
        return self.lines.count()

    def get_subtotal(self, item, **kwargs):
        return item.get_total(**kwargs)

    def get_total(self, **kwargs):
        subtotals = [self.get_subtotal(item, **kwargs)
                     for item in self.lines.all()]
        if not subtotals:
            raise AttributeError('Calling get_total() on an empty item set')
        zero = Price(0, currency=settings.DEFAULT_CURRENCY)
        return sum(subtotals, zero)

    def count(self):
        lines = self.lines.all()
        return lines.aggregate(total_quantity=models.Sum('quantity'))

    def clear(self):
        self.delete()

    def create_line(self, variant, quantity, data):
        line = self.lines.create(variant=variant, quantity=quantity,
                                 data=data or {})
        return line

    def get_line(self, variant, data=None):
        all_lines = self.lines.all()
        if data is None:
            data = {}
        line = [line for line in all_lines
                if line.variant_id == variant.id and line.data == data]
        if line:
            return line[0]

    def add(self, variant, quantity=1, data=None, replace=False,
            check_quantity=True):
        cart_line, created = self.lines.get_or_create(
            variant=variant, defaults={'quantity': 0, 'data': data or {}})
        if replace:
            new_quantity = quantity
        else:
            new_quantity = cart_line.quantity + quantity

        if new_quantity < 0:
            raise ValueError('%r is not a valid quantity (results in %r)' % (
                quantity, new_quantity))

        if check_quantity:
            variant.check_quantity(new_quantity)

        cart_line.quantity = new_quantity

        if not cart_line.quantity:
            cart_line.delete()
        else:
            cart_line.save(update_fields=['quantity'])
        self.update_quantity()

    def partition(self):
        grouper = (
            lambda p: 'physical' if p.is_shipping_required() else 'digital')
        return partition(self.lines.all(), grouper, ProductGroup)


@python_2_unicode_compatible
class CartLine(models.Model, ItemLine):

    cart = models.ForeignKey(
        Cart, related_name='lines',
        verbose_name=pgettext_lazy('Cart line field', 'cart'))
    variant = models.ForeignKey(
        'product.ProductVariant', related_name='+',
        verbose_name=pgettext_lazy('Cart line field', 'product'))
    quantity = models.PositiveIntegerField(
        pgettext_lazy('Cart line field', 'quantity'),
        validators=[MinValueValidator(0), MaxValueValidator(999)])
    data = JSONField(
        blank=True, default={},
        verbose_name=pgettext_lazy('Cart line field', 'data'))

    class Meta:
        unique_together = ('cart', 'variant', 'data')
        verbose_name = pgettext_lazy('Cart line model', 'Cart line')
        verbose_name_plural = pgettext_lazy('Cart line model', 'Cart lines')

    def __str__(self):
        return smart_str(self.variant)

    def __eq__(self, other):
        if not isinstance(other, CartLine):
            return NotImplemented

        return (self.variant == other.variant and
                self.quantity == other.quantity and
                self.data == other.data)

    def __ne__(self, other):
        return not self == other  # pragma: no cover

    def __repr__(self):
        return 'CartLine(variant=%r, quantity=%r, data=%r)' % (
            self.variant, self.quantity, self.data)

    def __getstate__(self):
        return self.variant, self.quantity, self.data

    def __setstate__(self, data):
        self.variant, self.quantity, self.data = data

    def get_total(self, **kwargs):
        amount = super(CartLine, self).get_total(**kwargs)
        return amount.quantize(CENTS)

    def get_quantity(self, **kwargs):
        return self.quantity

    def get_price_per_item(self, discounts=None, **kwargs):
        return self.variant.get_price_per_item(discounts=discounts, **kwargs)

    def is_shipping_required(self):
        return self.variant.is_shipping_required()

saleor/order/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import pgettext_lazy
from payments import PaymentStatus

from .models import Payment
from ..registration.forms import SignupForm


class PaymentMethodsForm(forms.Form):
    method = forms.ChoiceField(
        label=pgettext_lazy('Payment methods form label', 'Method'),
        choices=settings.CHECKOUT_PAYMENT_CHOICES, widget=forms.RadioSelect,
        initial=settings.CHECKOUT_PAYMENT_CHOICES[0][0])


class PaymentDeleteForm(forms.Form):
    payment_id = forms.IntegerField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        self.order = kwargs.pop('order')
        super(PaymentDeleteForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(PaymentDeleteForm, self).clean()
        payment_id = cleaned_data.get('payment_id')
        waiting_payments = self.order.payments.filter(
            status=PaymentStatus.WAITING)
        try:
            payment = waiting_payments.get(id=payment_id)
        except Payment.DoesNotExist:
            self._errors['number'] = self.error_class([
                pgettext_lazy(
                    'Payment delete form error',
                    'Payment does not exist')])
        else:
            cleaned_data['payment'] = payment
        return cleaned_data

    def save(self):
        payment = self.cleaned_data['payment']
        payment.status = PaymentStatus.REJECTED
        payment.save()


class PasswordForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super(PasswordForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = forms.HiddenInput()

templates/order/create_password.html
{% extends 'checkout/details.html' %}

{% load bootstrap_form from bootstrap3 %}
{% load staticfiles %}
{% load i18n %}

{% block title %}{% trans "Create password" context "Checkout create password page title" %} — {{ block.super }}{% endblock %}


{% block content %}
  <div class="row checkout__thankyoupage">
    <div class="col-xl-10 offset-xl-1">
      <img class="checkout__thankyoupage__parrot" src="{% static 'images/parrot.png' %}"
           srcset="{% static 'images/parrot.png' %} 1x, {% static 'images/parrot2x.png' %} 2x">
      <h1>{% blocktrans trimmed with order_url=order.get_absolute_url context "Checkout title" %}
          Thank you for your <a href="{{ order_url }}">order</a>!
      {% endblocktrans %}</h1>

        <p>{% blocktrans trimmed with order_url=order.get_absolute_url context "Checkout text" %}
          We've sent a confirmation email with details to <span>{{ email }}</span>.<br>
          If any problems or questions contact us.
        {% endblocktrans %}</p>
      <div class="row checkout__thankyoupage__form">
        <div class="col-md-6 push-md-6">
          {% if login_form is not None %}
            <p>{% blocktrans trimmed context "Checkout text" %}
              It looks like you already are our customer! <br>
              Please log in to connect order with your account.
            {% endblocktrans %}</p>
            {% url "order:connect-order-with-user" token=order.token as attach_url %}
            {% include "account/partials/login_form.html" with redirect_field_value=attach_url form=login_form %}
          {% else %}
            <form method="post" action="" novalidate>
              {% csrf_token %}
              <fieldset>
                <h3>{% trans "Why not to create an account" context "Checkout title" %}</h3>
                <p>{% blocktrans trimmed %}
                    Make your shopping experience even better!
                    Save your shipping and payment details for faster checkout.
                {% endblocktrans %}</p>
                {% bootstrap_form form %}
              </fieldset>
              <div class="row login__btn-group">
                <div class="col-12">
                  <button class="btn primary">
                    {% trans "Create an account" context "Checkout primary action" %}
                  </button>
                </div>
              </div>
            </form>
          {% endif %}
        </div>
        <div class="col-md-6 pull-md-6">
          <h3>...</h3>
          <img class="checkout-pirate" src="{% static 'images/pirate-checkout.png' %}"
               srcset="{% static 'images/pirate-checkout.png' %} 1x, {% static 'images/pirate-checkout2x.png' %} 2x">
          <p><a href="{% url 'checkout:index' %}" class="btn secondary">
              {% trans "Continue shopping" context "Checkout secondary action" %}
          </a></p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/order/details.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}

{% block title %}
    {% blocktrans trimmed context "Order details page title" %}
        Order {{ order }}
    {% endblocktrans %} — {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    {% if order.user == user %}
      <ul class="breadcrumbs list-unstyled">
        <li><a href="/">
            {% trans "Home" context "Main navigation item" %}
        </a></li>
        <li><a href="{% url "profile:details" %}">
            {% trans "Your account" context "Main navigation item" %}
        </a></li>
        <li><a href="{{ order.get_absolute_url }}">
            {% blocktrans trimmed context "Order details breadcrumb" %}
                Order {{ order }}
            {% endblocktrans %}
        </a></li>
      </ul>
    {% endif %}
{% endblock breadcrumb %}

{% block content %}
    {# This view is available by just knowing url,          #}
    {# so we don't show all details (like delivery address) #}
    {# unless current user is owner of the order.           #}

    <div class="row order-details">
        <div class="col-lg-10 offset-lg-1">
            <h2 class="order-details__header">
                {% blocktrans trimmed with order_status=order.get_status_display context "Order detail text" %}
                    Order {{ order }}: {{ order_status }}
                {% endblocktrans %}
            </h2>
            {% if not order.is_fully_paid %}
                {% if order.is_pre_authorized %}
                    <a href="{% url "order:payment" token=order.token %}" class="btn btn-link">
                        {% trans "Payment details" context "Order details link text" %}
                    </a>
                {% else %}
                    <a href="{% url "order:payment" token=order.token %}" class="btn primary">
                        {% trans "Pay for order" context "Order details primary action" %}
                    </a>
                {% endif %}
            {% endif %}
            {% include "order/order-details.html" %}
        </div>
    </div>
{% endblock content %}

templates/order/order-details.html
{% load i18n %}
{% load gross from prices_i18n %}
{% load discount_amount_for from prices %}
{% load product_first_image from product_images %}
{% load discount_as_negative from voucher %}


{% if order.user == user %}
  <div class="order-details__addresses">
    <div class="row">
          {% if order.is_shipping_required %}
      <div class="col-6">
        <h3>
            {% trans "Shipping address" context "Order details address title" %}
        </h3>
              <address>{% include "userprofile/snippets/address-short.html" with address=order.shipping_address %}</address>
      </div>
              {% endif %}
      <div class="col-6">
        <h3>
            {% trans "Billing address" context "Order details address title" %}
        </h3>
        <address>{% include "userprofile/snippets/address-short.html" with address=order.billing_address %}</address>
      </div>
    </div>
  </div>
{% endif %}
<div class="table__header hidden-sm-down">
  <div class="row">
    <div class="col-md-6">
      <small>
          {% trans "Product" context "Order details column title" %}
      </small>
    </div>
    <div class="col-md-3 text-right">
      <small>
          {% trans "Quantity" context "Order details column title" %}
      </small>
    </div>
    <div class="col-md-3 text-right">
      <small>
          {% trans "Price" context "Order details column title" %}
      </small>
    </div>
  </div>
</div>

  {% for item in order %}
    {% for item_line in item %}
      <div class="row">
        <div class="col-md-6 col-9">
          <a class="link--clean" href="{{ item_line.product.get_absolute_url }}">
            <img src="{% product_first_image item_line.product size="60x60" method="crop" %}" 
                 srcset="{% product_first_image item_line.product size="60x60" method="crop" %} 1x, {% product_first_image item_line.product size="120x120" method="crop" %} 2x" 
                 class="float-left">
            <p>{{ item_line.product }}<br>
            <span>{{ item_line.product_name }}</span></p>
          </a>
        </div>
        <div class="col-md-6 col-3">
          <div class="row">
            <div class="col-md-6 col-12">
              <p class="float-right">x {{ item_line.quantity }}</p>
            </div>
            <div class="col-md-6 col-12">
              <p class="float-right">{% gross item_line.get_total html=True %}</p>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    {% if order.is_shipping_required %}
        <div class="row">
          <div class="col-8">
            <p>
              {% blocktrans trimmed with shipping_method_name=item.shipping_method_name context "Order details delivery row text"  %}
                Delivery ({{ shipping_method_name }})
              {% endblocktrans %}
            </p>
            {% if item.tracking_number %}
              <p>
                {% blocktrans trimmed with tracking_number=item.tracking_number context "Order details delivery row text"  %}
                  Tracking number: {{ tracking_number }}
                {% endblocktrans %}
              </p>
            {% endif %}
          </div>
          <div class="col-4">
            <p class="float-right">{% gross item.shipping_price html=True %}</p>
          </div>
        </div>
    {% endif %}
    {% if order.discount_amount %}
      <div class="row">
        <div class="col-8">
          <p>{{ order.discount_name }}</p>
        </div>
        <div class="col-4">
          <p class="float-right">{% discount_as_negative order.discount %}</p>
        </div>
      </div>
    {% endif %}
    <div class="total">
      <div class="row">
        <div class="col-8">
          <div class="total">
            <p><strong>{% trans "Total" context "Order details total text" %}</strong></p>
          </div>
        </div>
        <div class="col-4">
          <p class="float-right"><strong>{% gross order.total html=True %}</strong></p>
        </div>
      </div>
    </div>
  {% endfor %}

templates/order/payment.html
{% extends "base.html" %}

{% load bootstrap_form from bootstrap3 %}
{% load gross from prices_i18n %}
{% load discount_amount_for from prices %}
{% load i18n %}
{% load staticfiles %}

{% block title %}
    {% blocktrans trimmed context "Payment details page title" %}
        Pay for order {{ order }}
    {% endblocktrans %} — {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    {% if order.user == user %}
    <ul class="breadcrumbs list-unstyled">
        <li><a href="/">
            {% trans "Home" context "Main navigation item" %}
        </a></li>
        <li><a href="{% url "profile:details" %}">
            {% trans "Your account" context "Main navigation item" %}
        </a></li>
        <li><a href="{{ order.get_absolute_url }}">
            {% blocktrans trimmed context "Payment details breadcrumb" %}
                Order {{ order }}
            {% endblocktrans %}
        </a></li>
    </ul>
    {% endif %}
{% endblock breadcrumb %}

{% block content %}
    <div class="row checkout">
        <div class="col-lg-10 offset-lg-1">
            {% if order.user == user or not order.is_fully_paid %}
                {% if not order.is_fully_paid %}
                       {% if waiting_payment %}
                            <h1>
                              {% trans "Payment pending" context "Payment details title" %}
                            </h1>
                            <form method="post" action="{% url 'order:cancel-payment' token=order.token %}" class="checkout-form">
                                {% csrf_token %}
                                <p>{% blocktrans trimmed context "Payment pending text" %}
                                    We are currently waiting for an external service to authorize
                                    your payment for this order.
                                {% endblocktrans %}</p>
                                <p>{% trans "Current status:" context "Payment status text" %}
                                    <br>
                                    <span class="label label-default">
                                    {{ waiting_payment.get_status_display }}
                                    </span>
                                </p>
                                <p>{%  blocktrans trimmed context "Payment pending text" %}
                                    Unless you are absolutely sure that the process will not complete
                                    (for example you have closed the browser window before paying),
                                    you should wait before attempting a new payment.
                                    Please be warned that if you try again and the previous
                                    transaction succeeds you might end up being charged twice.
                                {% endblocktrans %}</p>
                                {% bootstrap_form waiting_payment_form %}
                                <button type="submit" class="btn danger">
                                    {% trans "I understand, allow me to pay again" context "Payment pending action" %}
                                </button>
                            </form>
                        {% elif payment_form %}
                            <h1>
                                {% blocktrans trimmed context "Payment details title" %}
                                    Pay for order {{ order }}
                                {% endblocktrans %}
                            </h1>
                            <form method="post" action="{% url "order:payment" token=order.token %}" class="payment-method-form radio">
                              {% csrf_token %}
                              {{ payment_form }}
                              {% block form_submit %}
                                    <button type="submit" class="btn primary">
                                        {% trans "Proceed to payment" context "Payment details primary action" %}
                                    </button>
                              {% endblock %}
                            </form>
                        {% else %}
                            <p>{% trans "You've authorized transaction. Order is in processing" context "Payment details text" %}</p>
                        {% endif %}
                {% endif %}
            {% endif %}
            {% include 'order/order-details.html' %}
        </div>
    </div>
{% endblock content %}

templates/order/success.html
{% extends "base.html" %}
{% load gross from prices_i18n %}
{% load i18n %}

{% block title %}{% trans "Order complete!" %} — {{ block.super }}{% endblock %}


{% block content %}
<h2>{% trans "Your order is now complete" %}</h2>
<p>{% trans "Thank you for your purchase!" %}</p>

<p>{% trans "Your order number is" %}: <a href="{% url 'order:details' token=order.token %}">{{ order }}</a></p>
{% endblock content %}

{% block google-analytics-script %}
    {{ block.super }}
    __ga('require', 'ecommerce', 'ecommerce.js');
    __ga('set', 'currencyCode', '{{ DEFAULT_CURRENCY }}');
    __ga('ecommerce:addTransaction', {
      'id': '{{ order.id }}',
      'affiliation': 'Saleor',
      'revenue': '{{ order.get_total.gross }}',
      'shipping': '{{ order.get_delivery_total.gross }}',
      'tax': '{{ order.get_total.tax }}'
    });
    {% for item in order.get_items %}
     __ga('ecommerce:addItem', {
        'id': '{{ item.id }}',
        'name': '{{ item }}',
        'sku': '{{ item.sku }}',
        'category': '{{ item.product.category }}',
        'price': '{{ item.unit_price_gross }}',
        'quantity': '{{ item.quantity }}'
      });
    {% endfor %}
    __ga('ecommerce:send');
{% endblock google-analytics-script %}